name: network
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.3.2
  encrypt: ^5.0.2
  crypto: ^3.0.3
  hive: ^2.2.3
  uuid: ^4.0.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0